# SwiftLint Configuration for MUDRammer
# (Future-proofing for Swift migration)

# Paths to include/exclude
included:
  - src/Mudrammer
  - src/MRTests

excluded:
  - src/Pods
  - src/Carthage
  - output
  - vendor

# Disabled rules (adjust as needed)
disabled_rules:
  - trailing_whitespace  # Already handled by rake ws
  - todo  # Allow TODO comments during development

# Opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
  - first_where
  - sorted_imports
  - vertical_whitespace_closing_braces

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 40
  error: 100

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - i
    - j
    - k
    - x
    - y
    - id

# Reporter type
reporter: "xcode"
